# Bonsai - OpenBIM Blender Add-on
# River Ecosystem Model UI - Item 11 for Federation Panel

"""
River Ecosystem Model UI
------------------------
Dynamic 3D monitoring visualization for Klang River infrastructure.
Integrates with federated GI database for real-time ecosystem monitoring.
"""

import bpy
import os
from pathlib import Path
from bpy.types import Panel, Operator
import bonsai.tool as tool
from datetime import datetime
import sys


# =============================================================================
# REFERENCE DATA - Klang River Boom Stations (Hardcoded Golden Reference)
# =============================================================================
# This is the authoritative source for the 40 boom stations along Klang River
# Used to restore database if data gets corrupted or initialize first-time setup
# Coordinates follow the WINDING RIVER PATH from KlangInfo.jpg map
# Generated by klang_river_coordinates_from_map.py with realistic S-curve meander
#
# Users can manually edit positions in database - Reset only updates position_source='auto'
# Manual edits (position_source='manual') are preserved

KLANG_BOOM_STATIONS_REFERENCE = {
    1: {"name": "Boom Station 1_UPSTREAM", "x": -21834.0, "y": -3514.0, "z": 0.0, "zone": "upstream", "priority": "HIGH"},
    2: {"name": "Boom Station 2_UPSTREAM", "x": -20500.0, "y": -2800.0, "z": 0.0, "zone": "upstream", "priority": "HIGH"},
    3: {"name": "Boom Station 3_UPSTREAM", "x": -19200.0, "y": -1900.0, "z": 0.0, "zone": "upstream", "priority": "HIGH"},
    4: {"name": "Boom Station 4_UPSTREAM", "x": -17800.0, "y": -800.0, "z": 0.0, "zone": "upstream", "priority": "MEDIUM"},
    5: {"name": "Boom Station 5_UPSTREAM", "x": -16400.0, "y": 200.0, "z": 0.0, "zone": "upstream", "priority": "MEDIUM"},
    6: {"name": "Boom Station 6_UPSTREAM", "x": -15000.0, "y": 800.0, "z": 0.0, "zone": "upstream", "priority": "MEDIUM"},
    7: {"name": "Boom Station 7_UPSTREAM", "x": -13800.0, "y": 1200.0, "z": 0.0, "zone": "upstream", "priority": "MEDIUM"},
    8: {"name": "Boom Station 8_UPSTREAM", "x": -12600.0, "y": 1800.0, "z": 0.0, "zone": "upstream", "priority": "MEDIUM"},
    9: {"name": "Boom Station 9_UPSTREAM", "x": -11400.0, "y": 2600.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    10: {"name": "Boom Station 10_UPSTREAM", "x": -10200.0, "y": 3400.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    11: {"name": "Boom Station 11_UPSTREAM", "x": -9000.0, "y": 3800.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    12: {"name": "Boom Station 12_UPSTREAM", "x": -7800.0, "y": 3600.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    13: {"name": "Boom Station 13_UPSTREAM", "x": -6800.0, "y": 3000.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    14: {"name": "Boom Station 14_UPSTREAM", "x": -6000.0, "y": 2400.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    15: {"name": "Boom Station 15_UPSTREAM", "x": -5400.0, "y": 2000.0, "z": 0.0, "zone": "upstream", "priority": "LOW"},
    16: {"name": "Boom Station 16_MIDSTREAM", "x": -4800.0, "y": 2800.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    17: {"name": "Boom Station 17_MIDSTREAM", "x": -4000.0, "y": 3600.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    18: {"name": "Boom Station 18_MIDSTREAM", "x": -3200.0, "y": 4400.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    19: {"name": "Boom Station 19_MIDSTREAM", "x": -2400.0, "y": 5200.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    20: {"name": "Boom Station 20_MIDSTREAM", "x": -1600.0, "y": 6000.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    21: {"name": "Boom Station 21_MIDSTREAM", "x": -800.0, "y": 6800.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    22: {"name": "Boom Station 22_MIDSTREAM", "x": 0.0, "y": 7600.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    23: {"name": "Boom Station 23_MIDSTREAM", "x": 800.0, "y": 8400.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    24: {"name": "Boom Station 24_MIDSTREAM", "x": 1600.0, "y": 9200.0, "z": 0.0, "zone": "midstream", "priority": "HIGH"},
    25: {"name": "Boom Station 25_MIDSTREAM", "x": 2400.0, "y": 9800.0, "z": 0.0, "zone": "midstream", "priority": "MEDIUM"},
    26: {"name": "Boom Station 26_MIDSTREAM", "x": 3200.0, "y": 10200.0, "z": 0.0, "zone": "midstream", "priority": "MEDIUM"},
    27: {"name": "Boom Station 27_MIDSTREAM", "x": 4000.0, "y": 10400.0, "z": 0.0, "zone": "midstream", "priority": "MEDIUM"},
    28: {"name": "Boom Station 28_MIDSTREAM", "x": 4800.0, "y": 10600.0, "z": 0.0, "zone": "midstream", "priority": "MEDIUM"},
    29: {"name": "Boom Station 29_MIDSTREAM", "x": 5600.0, "y": 10900.0, "z": 0.0, "zone": "midstream", "priority": "MEDIUM"},
    30: {"name": "Boom Station 30_MIDSTREAM", "x": 6400.0, "y": 11300.0, "z": 0.0, "zone": "midstream", "priority": "MEDIUM"},
    31: {"name": "Boom Station 31_DOWNSTREAM", "x": 7200.0, "y": 11800.0, "z": 0.0, "zone": "downstream", "priority": "HIGH"},
    32: {"name": "Boom Station 32_DOWNSTREAM", "x": 8000.0, "y": 12300.0, "z": 0.0, "zone": "downstream", "priority": "HIGH"},
    33: {"name": "Boom Station 33_DOWNSTREAM", "x": 8800.0, "y": 12700.0, "z": 0.0, "zone": "downstream", "priority": "HIGH"},
    34: {"name": "Boom Station 34_DOWNSTREAM", "x": 9600.0, "y": 13000.0, "z": 0.0, "zone": "downstream", "priority": "HIGH"},
    35: {"name": "Boom Station 35_DOWNSTREAM", "x": 10400.0, "y": 13300.0, "z": 0.0, "zone": "downstream", "priority": "HIGH"},
    36: {"name": "Boom Station 36_DOWNSTREAM", "x": 11200.0, "y": 13600.0, "z": 0.0, "zone": "downstream", "priority": "MEDIUM"},
    37: {"name": "Boom Station 37_DOWNSTREAM", "x": 12000.0, "y": 13900.0, "z": 0.0, "zone": "downstream", "priority": "MEDIUM"},
    38: {"name": "Boom Station 38_DOWNSTREAM", "x": 12800.0, "y": 14200.0, "z": 0.0, "zone": "downstream", "priority": "LOW"},
    39: {"name": "Boom Station 39_DOWNSTREAM", "x": 13300.0, "y": 14500.0, "z": 0.0, "zone": "downstream", "priority": "LOW"},
    40: {"name": "Boom Station 40_DOWNSTREAM", "x": 13853.0, "y": 14723.0, "z": 0.0, "zone": "downstream", "priority": "LOW"},
}


# =============================================================================
# LOGGING UTILITY
# =============================================================================

class RiverEcosystemLogger:
    """Logger that writes to both console and file"""

    def __init__(self, operator_name):
        self.operator_name = operator_name
        self.step = 0

        # Setup log file (single persistent file that updates)
        log_dir = Path.home() / "Documents" / "bonsai" / "consolelogs"
        log_dir.mkdir(parents=True, exist_ok=True)

        # Use single log file instead of timestamped
        self.log_file = log_dir / "river_ecosystem_latest.txt"

        # Clear previous log and write header
        header = f"""
{'='*70}
RIVER ECOSYSTEM MODEL - {operator_name}
{'='*70}
Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Log File: {self.log_file}
{'='*70}
"""
        # Overwrite file with header
        with open(self.log_file, 'w') as f:
            f.write(header + '\n')
        print(header)

    def _write(self, message):
        """Write to file"""
        try:
            with open(self.log_file, 'a') as f:
                f.write(message + '\n')
        except Exception as e:
            print(f"Warning: Could not write to log file: {e}")

    def log(self, message, error=False):
        """Log message to both console and file"""
        self.step += 1
        prefix = "❌" if error else "→"
        formatted = f"{self.step:3d}. {prefix} {message}"

        # Write to both console and file
        print(formatted)
        self._write(formatted)

        return formatted

    def section(self, title):
        """Log a section header"""
        line = f"\n{'-'*70}"
        header = f"{title}"
        formatted = f"{line}\n{header}\n{line}"

        print(formatted)
        self._write(formatted)

    def summary(self, success, message):
        """Log final summary"""
        symbol = "✅" if success else "❌"
        summary = f"""
{'='*70}
{symbol} {message}
{'='*70}
Log saved to: {self.log_file}
"""
        print(summary)
        self._write(summary)


class BIM_PT_river_ecosystem(Panel):
    """River Ecosystem Model - Dynamic 3D monitoring for Klang River"""
    bl_label = "11. River Ecosystem Model"
    bl_idname = "BIM_PT_river_ecosystem"
    bl_space_type = "PROPERTIES"
    bl_region_type = "WINDOW"
    bl_context = "scene"
    bl_parent_id = "BIM_PT_tabs"
    bl_options = {"DEFAULT_CLOSED"}
    bl_order = 11

    # No poll needed - always show in Project Overview

    def draw(self, context):
        layout = self.layout
        props = context.scene.BIMFederationProperties

        # Header Box - River System Status
        header_box = layout.box()
        header_box.label(text="🌊 Klang River Ecosystem", icon="WORLD")

        if props.index_loaded and "klang" in props.federation_database_path.lower():
            col = header_box.column(align=True)
            col.label(text="✓ River Database Loaded", icon="CHECKMARK")
            col.label(text="56km river system • 40 boom stations")
        else:
            col = header_box.column(align=True)
            col.label(text="⚠ Load klang_river_perfect.db first", icon="ERROR")
            col.label(text="Database: WORK_DIR/RIVER/")

        layout.separator()

        # Database Test & Clear - TOP PRIORITY
        tools_box = layout.box()
        tools_box.label(text="Database Tools", icon="TOOL_SETTINGS")

        row = tools_box.row(align=True)
        row.scale_y = 1.3
        row.operator("bim.test_river_database",
                    icon="VIEWZOOM",
                    text="Test")
        row.operator("bim.reset_boom_stations",
                    icon="FILE_REFRESH",
                    text="Setup/Reset")
        row.operator("bim.clear_ecosystem_model",
                    icon="TRASH",
                    text="Clear Scene")

        # Workflow hint
        col = tools_box.column(align=True)
        col.scale_y = 0.7
        col.label(text="First time? Click 'Setup/Reset' to initialize", icon="INFO")

        layout.separator()

        # Main Monitoring Systems
        monitor_box = layout.box()
        monitor_box.label(text="Monitoring Systems", icon="GRAPH")

        col = monitor_box.column(align=True)

        # Realistic Monitor (Main)
        row = col.row()
        row.scale_y = 1.5
        row.operator("bim.run_klang_realistic_monitor",
                    icon="OUTLINER_OB_LIGHT",
                    text="Launch Realistic Monitor")

        col.label(text="• 3 Zones: Upstream, Midstream, Downstream")
        col.label(text="• DOE water quality parameters")
        col.label(text="• Real-time 3D bar charts")

        layout.separator()

        # Infrastructure Monitor
        infra_box = layout.box()
        infra_box.label(text="Infrastructure Systems", icon="MOD_BUILD")

        col = infra_box.column(align=True)

        row = col.row()
        row.scale_y = 1.3
        row.operator("bim.run_infrastructure_model",
                    icon="SETTINGS",
                    text="Infrastructure Model")

        col.label(text="• CSOs, Weirs, Tide Gates")
        col.label(text="• Pump Houses, Treatment Plants")
        col.label(text="• Industry-standard metrics")

        layout.separator()

        # Storm Simulation
        storm_box = layout.box()
        storm_box.label(text="Crisis Management", icon="FORCE_WIND")

        col = storm_box.column(align=True)

        row = col.row()
        row.scale_y = 1.3
        row.operator("bim.run_storm_simulation",
                    icon="LIGHT_HEMI",
                    text="Storm Event Simulation")

        col.label(text="• Integrated response coordination")
        col.label(text="• 5 phases: Normal → Crisis → Recovery")
        col.label(text="• All systems responding in sync")

        layout.separator()

        # Additional Features
        features_box = layout.box()
        features_box.label(text="Ecosystem Features", icon="SCENE_DATA")

        col = features_box.column(align=True)

        # Basic monitor
        row = col.row(align=True)
        row.operator("bim.run_basic_ecosystem",
                    icon="VIEW3D",
                    text="Basic Monitor")

        layout.separator()

        # Value Metrics
        value_box = layout.box()
        value_box.label(text="Value Generation", icon="FUND")

        col = value_box.column(align=True)
        col.scale_y = 0.9
        col.label(text="• Plastic Recovery: RM 43-197M/year")
        col.label(text="• Flood Prevention: RM 50-100M/year")
        col.label(text="• Energy Savings: RM 5-10M/year")
        col.label(text="• Total Value: RM 110-332M/year")

        layout.separator()

        # Quick Info
        info_box = layout.box()
        info_box.label(text="Quick Start:", icon="INFO")
        col = info_box.column(align=True)
        col.scale_y = 0.8
        col.label(text="1. Load klang_river_perfect.db")
        col.label(text="2. Launch Realistic Monitor")
        col.label(text="3. Press SPACE to animate")
        col.label(text="4. Click bars for details")
        col.label(text="5. Use Outliner to toggle zones")


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def clear_ecosystem_objects():
    """Helper function to clear existing ecosystem objects before re-running
    Preserves: IFC elements (river geometry), cameras, lights
    Removes: Ecosystem monitoring objects (booms, bars, platforms, text)
    """
    collection_names = [
        "KLANG_RIVER_ECOSYSTEM",
        "KLANG_INFRASTRUCTURE",
        "STORM_SIMULATION",
        "RIVER_ECOSYSTEM_MODEL",
        "BOOM_STATION_01",
        "TEST_RIVER_MONITOR",
        "RIVER_TEST",
        "KLANG_RIVER_DEBUG",
    ]

    zone_patterns = ["ZONE_", "BOOM_", "_upstream", "_midstream", "_downstream",
                    "TEST_BOOM", "FALLBACK_BOOM", "EMERGENCY_BOOM", "_UPSTREAM", "_MIDSTREAM", "_DOWNSTREAM"]

    removed_collections = 0
    removed_objects = 0

    # Remove predefined collections
    for name in collection_names:
        if name in bpy.data.collections:
            collection = bpy.data.collections[name]
            for obj in list(collection.objects):
                # Skip IFC elements (they have 'ifc_definition_id' property)
                if 'ifc_definition_id' not in obj:
                    bpy.data.objects.remove(obj, do_unlink=True)
                    removed_objects += 1
            # Remove collection if empty
            if len(collection.objects) == 0:
                bpy.data.collections.remove(collection)
                removed_collections += 1

    # Remove zone/boom pattern collections
    for col_name in list(bpy.data.collections.keys()):
        if any(pattern in col_name for pattern in zone_patterns):
            collection = bpy.data.collections[col_name]
            for obj in list(collection.objects):
                # Skip IFC elements
                if 'ifc_definition_id' not in obj:
                    bpy.data.objects.remove(obj, do_unlink=True)
                    removed_objects += 1
            # Remove collection if empty
            if len(collection.objects) == 0:
                bpy.data.collections.remove(collection)
                removed_collections += 1

    return removed_collections, removed_objects


# =============================================================================
# OPERATORS
# =============================================================================

class BIM_OT_run_klang_realistic_monitor(Operator):
    """Launch Klang River realistic monitoring with actual water quality parameters"""
    bl_idname = "bim.run_klang_realistic_monitor"
    bl_label = "Run Klang River Monitor"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        logger = RiverEcosystemLogger("KLANG RIVER MONITOR")

        try:
            # Auto-clear previous visualization
            cleared_cols, cleared_objs = clear_ecosystem_objects()
            if cleared_cols > 0:
                logger.log(f"Auto-cleared {cleared_cols} collections, {cleared_objs} objects")

            logger.section("SCRIPT VALIDATION")

            # Check script path
            script_path = Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/RiverEcoModel/klang_river_realistic_monitor.py")
            logger.log(f"Script path: {script_path}")
            logger.log(f"Script exists: {script_path.exists()}")

            if not script_path.exists():
                logger.log(f"Script not found!", error=True)
                logger.summary(False, "FAILED - Script not found")
                self.report({'ERROR'}, f"Script not found: {script_path}")
                return {'CANCELLED'}

            logger.log("Reading script file...")
            with open(script_path, 'r') as f:
                script_content = f.read()
            logger.log(f"Script size: {len(script_content)} bytes")

            logger.section("SCENE STATE - BEFORE EXECUTION")

            # Check collections before
            initial_collections = list(bpy.data.collections.keys())
            initial_objects = len(bpy.data.objects)
            logger.log(f"Collections before: {len(initial_collections)}")
            logger.log(f"Objects before: {initial_objects}")

            logger.section("EXECUTING SCRIPT")

            # Execute the script
            logger.log("Starting script execution...")
            exec_globals = {'__name__': '__main__'}
            # DISABLED: Auto-execution removed - scripts must be triggered manually via button
            # exec(script_content, exec_globals)
            logger.log("⚠️  Auto-execution disabled - script ready but not run")
            self.report({'WARNING'}, "Auto-exec disabled - use button to run scripts manually")

            logger.section("SCENE STATE - AFTER EXECUTION")

            # Check what was created
            final_collections = list(bpy.data.collections.keys())
            final_objects = len(bpy.data.objects)
            new_collections = [c for c in final_collections if c not in initial_collections]

            logger.log(f"Collections after: {len(final_collections)}")
            logger.log(f"Objects after: {final_objects}")
            logger.log(f"New collections created: {len(new_collections)}")

            if new_collections:
                logger.log("New collections:")
                for col_name in new_collections[:5]:  # Show first 5
                    col = bpy.data.collections[col_name]
                    logger.log(f"  - {col_name}: {len(col.objects)} objects")

            objects_created = final_objects - initial_objects
            logger.log(f"Objects created: {objects_created}")

            # Check for specific collections
            expected = ["KLANG_RIVER_ECOSYSTEM", "ZONE_UPSTREAM", "ZONE_MIDSTREAM", "ZONE_DOWNSTREAM"]
            found = [name for name in expected if name in bpy.data.collections]
            logger.log(f"Expected collections found: {len(found)}/{len(expected)}")

            if objects_created > 0:
                logger.log(f"SUCCESS: Created {objects_created} objects")
                self.report({'INFO'}, f"✓ Monitor launched - {objects_created} objects created")

                # Try to frame view
                logger.log("Attempting to frame view...")
                try:
                    for area in context.screen.areas:
                        if area.type == 'VIEW_3D':
                            with context.temp_override(area=area):
                                bpy.ops.view3d.view_all()
                            logger.log("View framed")
                            break
                except Exception as e:
                    logger.log(f"Could not auto-frame view: {e}")

                logger.summary(True, f"SUCCESS - {objects_created} objects created")
                return {'FINISHED'}
            else:
                logger.log("WARNING: No objects were created", error=True)
                logger.summary(False, "WARNING - No objects created")
                self.report({'WARNING'}, "Monitor executed but no objects created")
                return {'FINISHED'}

        except Exception as e:
            logger.log(f"EXCEPTION: {str(e)}", error=True)
            import traceback
            tb_str = traceback.format_exc()
            logger.log("TRACEBACK:")
            logger._write(tb_str)
            print(tb_str)
            logger.summary(False, f"FAILED - Exception: {str(e)}")
            self.report({'ERROR'}, f"Failed: {str(e)}")
            return {'CANCELLED'}


class BIM_OT_run_infrastructure_model(Operator):
    """Launch infrastructure model with CSOs, weirs, pumps, treatment plants"""
    bl_idname = "bim.run_infrastructure_model"
    bl_label = "Run Infrastructure Model"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        logger = RiverEcosystemLogger("INFRASTRUCTURE MODEL")

        try:
            # Auto-clear previous visualization
            cleared_cols, cleared_objs = clear_ecosystem_objects()
            if cleared_cols > 0:
                logger.log(f"Auto-cleared {cleared_cols} collections, {cleared_objs} objects")

            script_path = Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/RiverEcoModel/klang_infrastructure_model.py")
            logger.log(f"Script path: {script_path}")
            logger.log(f"Script exists: {script_path.exists()}")

            if not script_path.exists():
                logger.log("Script not found!", error=True)
                logger.summary(False, "FAILED - Script not found")
                self.report({'ERROR'}, f"Script not found: {script_path}")
                return {'CANCELLED'}

            initial_objects = len(bpy.data.objects)
            logger.log(f"Objects before: {initial_objects}")

            with open(script_path, 'r') as f:
                script_content = f.read()

            logger.log(f"Script ready ({len(script_content)} bytes)...")
            # DISABLED: Auto-execution removed - scripts must be triggered manually
            # exec(script_content, {'__name__': '__main__'})

            final_objects = len(bpy.data.objects)
            created = final_objects - initial_objects
            logger.log(f"Objects created: {created}")

            if created > 0:
                logger.summary(True, f"SUCCESS - {created} infrastructure objects")
                self.report({'INFO'}, f"✓ Infrastructure Model - {created} objects")
            else:
                logger.summary(False, "WARNING - No objects created")
                self.report({'WARNING'}, "Infrastructure script ran but no objects created")

            return {'FINISHED'}

        except Exception as e:
            logger.log(f"ERROR: {e}", error=True)
            import traceback
            logger._write(traceback.format_exc())
            traceback.print_exc()
            logger.summary(False, f"FAILED - {str(e)}")
            self.report({'ERROR'}, f"Failed: {str(e)}")
            return {'CANCELLED'}


class BIM_OT_run_storm_simulation(Operator):
    """Simulate storm event showing integrated infrastructure response"""
    bl_idname = "bim.run_storm_simulation"
    bl_label = "Run Storm Simulation"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        logger = RiverEcosystemLogger("STORM SIMULATION")

        try:
            # Auto-clear previous visualization
            cleared_cols, cleared_objs = clear_ecosystem_objects()
            if cleared_cols > 0:
                logger.log(f"Auto-cleared {cleared_cols} collections, {cleared_objs} objects")

            script_path = Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/RiverEcoModel/test_storm_scenario.py")
            logger.log(f"Script path: {script_path}")
            logger.log(f"Script exists: {script_path.exists()}")

            if not script_path.exists():
                logger.log("Script not found!", error=True)
                logger.summary(False, "FAILED - Script not found")
                self.report({'ERROR'}, f"Script not found: {script_path}")
                return {'CANCELLED'}

            initial_objects = len(bpy.data.objects)
            logger.log(f"Objects before: {initial_objects}")

            with open(script_path, 'r') as f:
                script_content = f.read()

            logger.log(f"Storm simulation ready ({len(script_content)} bytes)...")
            # DISABLED: Auto-execution removed - scripts must be triggered manually
            # exec(script_content, {'__name__': '__main__'})

            final_objects = len(bpy.data.objects)
            created = final_objects - initial_objects
            logger.log(f"Objects created: {created}")

            if created > 0:
                logger.summary(True, f"SUCCESS - {created} storm objects created")
                self.report({'INFO'}, f"✓ Storm simulation - {created} objects - Use Timeline to animate")
            else:
                logger.summary(False, "WARNING - No objects created")
                self.report({'WARNING'}, "Storm script ran but no objects created")

            return {'FINISHED'}

        except Exception as e:
            logger.log(f"ERROR: {e}", error=True)
            import traceback
            logger._write(traceback.format_exc())
            traceback.print_exc()
            logger.summary(False, f"FAILED - {str(e)}")
            self.report({'ERROR'}, f"Failed: {str(e)}")
            return {'CANCELLED'}


class BIM_OT_run_basic_ecosystem(Operator):
    """Launch basic ecosystem monitor with 6 parameters"""
    bl_idname = "bim.run_basic_ecosystem"
    bl_label = "Run Basic Monitor"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        print("\n" + "="*70)
        print("RIVER ECOSYSTEM UI - BASIC MONITOR OPERATOR")
        print("="*70)

        try:
            script_paths = [
                Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/RiverEcoModel/river_ecosystem_monitor.py"),
                Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/scripts/river_ecosystem_monitor.py"),
            ]

            script_path = None
            for path in script_paths:
                print(f"Checking: {path}")
                if path.exists():
                    script_path = path
                    print(f"✓ Found script at: {path}")
                    break

            if not script_path:
                print("❌ No basic monitor script found in any location")
                self.report({'ERROR'}, "Basic monitor script not found")
                return {'CANCELLED'}

            initial_objects = len(bpy.data.objects)
            print(f"Objects before: {initial_objects}")

            with open(script_path, 'r') as f:
                script_content = f.read()

            print(f"Script ready ({len(script_content)} bytes)...")
            # DISABLED: Auto-execution removed - scripts must be triggered manually
            # exec(script_content, {'__name__': '__main__'})

            final_objects = len(bpy.data.objects)
            created = final_objects - initial_objects
            print(f"Objects created: {created}")

            if created > 0:
                print(f"✓ SUCCESS: {created} objects")
                self.report({'INFO'}, f"✓ Basic monitor - {created} objects")
            else:
                print("⚠ No objects created")

            print("="*70)
            return {'FINISHED'}

        except Exception as e:
            print(f"❌ ERROR: {e}")
            import traceback
            traceback.print_exc()
            print("="*70)
            self.report({'ERROR'}, f"Failed: {str(e)}")
            return {'CANCELLED'}


class BIM_OT_test_river_database(Operator):
    """Test river database integrity and show available data (read-only)"""
    bl_idname = "bim.test_river_database"
    bl_label = "Test River Database"
    bl_options = {"REGISTER"}

    def execute(self, context):
        import sqlite3

        logger = RiverEcosystemLogger("DATABASE INTEGRITY TEST")

        db_path = Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/klang_river_perfect.db")

        if not db_path.exists():
            logger.log(f"Database not found: {db_path}", error=True)
            logger.summary(False, "FAILED - Database not found")
            self.report({'ERROR'}, "Database not found")
            return {'CANCELLED'}

        try:
            conn = sqlite3.connect(db_path)
            cursor = conn.cursor()

            logger.section("DATABASE CONNECTION")
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
            tables = [row[0] for row in cursor.fetchall()]
            logger.log(f"Database connected: {len(tables)} tables")
            logger.log(f"Database size: {db_path.stat().st_size / 1024 / 1024:.2f} MB")

            issues = []  # Track integrity issues

            # ============================================================
            logger.section("BOOM STATIONS VALIDATION")
            # ============================================================

            cursor.execute("SELECT COUNT(*) FROM project_markers WHERE marker_type = 'boom_trap';")
            boom_count = cursor.fetchone()[0]
            logger.log(f"Total boom stations: {boom_count}")

            if boom_count == 0:
                issues.append("No boom stations found - Run 'Setup/Reset' to initialize")
                logger.log("❌ ERROR: No boom stations in database!", error=True)
                logger.log("➜ ACTION REQUIRED: Click 'Setup/Reset' button to initialize 40 boom stations")
                logger.log("➜ This is normal for first-time setup")
            else:
                # Check for valid coordinates
                cursor.execute("""
                    SELECT COUNT(*) FROM project_markers
                    WHERE marker_type = 'boom_trap'
                    AND (location_x IS NULL OR location_y IS NULL OR location_z IS NULL)
                """)
                null_coords = cursor.fetchone()[0]
                if null_coords > 0:
                    issues.append(f"{null_coords} boom stations with NULL coordinates")
                    logger.log(f"ERROR: {null_coords} stations with NULL coordinates", error=True)
                else:
                    logger.log("✓ All boom stations have valid coordinates")

                # Get coordinate ranges
                cursor.execute("""
                    SELECT MIN(location_x), MAX(location_x),
                           MIN(location_y), MAX(location_y),
                           MIN(location_z), MAX(location_z)
                    FROM project_markers WHERE marker_type = 'boom_trap';
                """)
                bounds = cursor.fetchone()
                logger.log(f"X range: {bounds[0]:.1f} to {bounds[1]:.1f} ({bounds[1]-bounds[0]:.1f}m span)")
                logger.log(f"Y range: {bounds[2]:.1f} to {bounds[3]:.1f} ({bounds[3]-bounds[2]:.1f}m span)")
                logger.log(f"Z range: {bounds[4]:.1f} to {bounds[5]:.1f}")

                # Check for duplicate names
                cursor.execute("""
                    SELECT name, COUNT(*) FROM project_markers
                    WHERE marker_type = 'boom_trap'
                    GROUP BY name HAVING COUNT(*) > 1
                """)
                duplicates = cursor.fetchall()
                if duplicates:
                    issues.append(f"{len(duplicates)} duplicate boom names")
                    logger.log(f"WARNING: {len(duplicates)} duplicate names", error=True)
                    for name, count in duplicates[:3]:
                        logger.log(f"  - '{name}' appears {count} times")
                else:
                    logger.log("✓ No duplicate boom names")

                # Check spacing (should be ~900m apart on average for 56km / 40 stations)
                cursor.execute("""
                    SELECT marker_id, location_x, location_y FROM project_markers
                    WHERE marker_type = 'boom_trap' ORDER BY marker_id
                """)
                stations = cursor.fetchall()
                if len(stations) > 1:
                    import math
                    distances = []
                    for i in range(len(stations) - 1):
                        dx = stations[i+1][1] - stations[i][1]
                        dy = stations[i+1][2] - stations[i][2]
                        dist = math.sqrt(dx*dx + dy*dy)
                        distances.append(dist)

                    avg_dist = sum(distances) / len(distances)
                    min_dist = min(distances)
                    max_dist = max(distances)

                    logger.log(f"Station spacing: avg={avg_dist:.1f}m, min={min_dist:.1f}m, max={max_dist:.1f}m")

                    if min_dist < 100:
                        issues.append(f"Stations too close: {min_dist:.1f}m minimum")
                        logger.log(f"WARNING: Minimum spacing {min_dist:.1f}m is very close", error=True)

            # ============================================================
            logger.section("WATER ELEMENT VALIDATION")
            # ============================================================

            cursor.execute("SELECT COUNT(*) FROM elements_meta WHERE ifc_class = 'IfcGeographicElement';")
            water_count = cursor.fetchone()[0]
            logger.log(f"Water elements (IfcGeographicElement): {water_count}")

            if water_count == 0:
                issues.append("No water element found")
                logger.log("ERROR: No water element found", error=True)
            else:
                cursor.execute("""
                    SELECT t.bbox_min_x, t.bbox_max_x,
                           t.bbox_min_y, t.bbox_max_y,
                           t.bbox_min_z, t.bbox_max_z,
                           m.name
                    FROM element_transforms t
                    JOIN elements_meta m ON t.guid = m.guid
                    WHERE m.ifc_class = 'IfcGeographicElement'
                    LIMIT 1;
                """)
                water_data = cursor.fetchone()
                if water_data:
                    water_bounds = water_data[:6]
                    water_name = water_data[6]
                    logger.log(f"Water name: {water_name}")
                    logger.log(f"X range: {water_bounds[0]:.1f} to {water_bounds[1]:.1f}")
                    logger.log(f"Y range: {water_bounds[2]:.1f} to {water_bounds[3]:.1f}")
                    logger.log(f"Z range: {water_bounds[4]:.1f} to {water_bounds[5]:.1f}")

                    # Check if boom stations are within water bounds (with tolerance)
                    if boom_count > 0:
                        cursor.execute("""
                            SELECT COUNT(*) FROM project_markers
                            WHERE marker_type = 'boom_trap'
                            AND (location_x < ? OR location_x > ?
                                 OR location_y < ? OR location_y > ?)
                        """, (water_bounds[0] - 1000, water_bounds[1] + 1000,
                              water_bounds[2] - 1000, water_bounds[3] + 1000))

                        outside = cursor.fetchone()[0]
                        if outside > 0:
                            issues.append(f"{outside} boom stations outside water bounds")
                            logger.log(f"WARNING: {outside} stations outside water bounds (+1km tolerance)", error=True)
                        else:
                            logger.log("✓ All boom stations within water element bounds")

            # ============================================================
            logger.section("ELEMENTS INVENTORY")
            # ============================================================

            cursor.execute("SELECT COUNT(*) FROM elements_meta;")
            total_elements = cursor.fetchone()[0]
            logger.log(f"Total elements: {total_elements}")

            if total_elements == 0:
                issues.append("No elements in database")
                logger.log("ERROR: Database is empty", error=True)

            # Check disciplines
            cursor.execute("SELECT discipline, COUNT(*) FROM elements_meta GROUP BY discipline ORDER BY COUNT(*) DESC;")
            disciplines = cursor.fetchall()
            logger.log(f"Disciplines: {len(disciplines)}")
            for disc, count in disciplines:
                logger.log(f"  - {disc}: {count} elements")

            # Check for orphaned transforms
            cursor.execute("""
                SELECT COUNT(*) FROM element_transforms t
                WHERE NOT EXISTS (
                    SELECT 1 FROM elements_meta m WHERE m.guid = t.guid
                )
            """)
            orphaned = cursor.fetchone()[0]
            if orphaned > 0:
                issues.append(f"{orphaned} orphaned transforms")
                logger.log(f"WARNING: {orphaned} transforms without metadata", error=True)
            else:
                logger.log("✓ No orphaned transforms")

            # ============================================================
            logger.section("INTEGRITY SUMMARY")
            # ============================================================

            conn.close()

            if len(issues) == 0:
                logger.log("✓ ALL CHECKS PASSED")
                logger.log("✓ Database integrity: EXCELLENT")
                logger.log(f"✓ Ready for visualization: {boom_count} booms, {total_elements} elements")
                logger.summary(True, f"PASSED - {boom_count} booms, {total_elements} elements, 0 issues")
                self.report({'INFO'}, f"✓ DB Perfect: {boom_count} booms, 0 issues")
                return {'FINISHED'}
            else:
                logger.log(f"⚠ {len(issues)} ISSUES FOUND:")
                for issue in issues:
                    logger.log(f"  - {issue}", error=True)
                logger.summary(False, f"ISSUES FOUND - {len(issues)} problems detected")
                self.report({'WARNING'}, f"⚠ DB has {len(issues)} issues - check console log")
                return {'FINISHED'}

        except Exception as e:
            logger.log(f"EXCEPTION: {str(e)}", error=True)
            import traceback
            tb_str = traceback.format_exc()
            logger._write(tb_str)
            print(tb_str)
            logger.summary(False, f"FAILED - {str(e)}")
            self.report({'ERROR'}, f"Database error: {str(e)}")
            return {'CANCELLED'}


class BIM_OT_reset_boom_stations(Operator):
    """Setup/Reset boom stations from hardcoded reference (initial setup or repair corruption)"""
    bl_idname = "bim.reset_boom_stations"
    bl_label = "Setup/Reset Boom Stations"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        import sqlite3

        logger = RiverEcosystemLogger("SETUP/RESET BOOM STATIONS")

        db_path = Path("/home/red1/Projects/IfcOpenShell/WORK_DIR/RIVER/klang_river_perfect.db")

        if not db_path.exists():
            logger.log(f"Database not found: {db_path}", error=True)
            logger.summary(False, "FAILED - Database not found")
            self.report({'ERROR'}, "Database not found")
            return {'CANCELLED'}

        try:
            conn = sqlite3.connect(db_path)
            cursor = conn.cursor()

            # Count existing boom stations
            cursor.execute("SELECT COUNT(*) FROM project_markers WHERE marker_type = 'boom_trap';")
            existing_count = cursor.fetchone()[0]

            if existing_count == 0:
                logger.section("INITIAL SETUP - No existing boom stations")
                logger.log("This is the first time setup")
                logger.log(f"Will create {len(KLANG_BOOM_STATIONS_REFERENCE)} boom stations from reference")
            else:
                logger.section("RESET - Replacing existing boom stations")
                logger.log(f"Found {existing_count} existing boom stations")
                logger.log("Will replace with reference data")

            if existing_count > 0:
                # Backup before deletion
                cursor.execute("""
                    SELECT marker_id, name, location_x, location_y FROM project_markers
                    WHERE marker_type = 'boom_trap'
                    ORDER BY marker_id
                    LIMIT 5
                """)
                sample = cursor.fetchall()
                logger.log(f"Sample of existing data (first 5):")
                for row in sample:
                    logger.log(f"  ID {row[0]}: {row[1]} at ({row[2]:.1f}, {row[3]:.1f})")

            logger.section("RESETTING TO REFERENCE DATA")

            # Check for position_source column (might not exist in old DBs)
            cursor.execute("PRAGMA table_info(project_markers)")
            columns = [row[1] for row in cursor.fetchall()]
            has_position_source = 'position_source' in columns

            if existing_count == 0:
                # Fresh setup - insert all
                logger.log("Fresh setup - inserting all boom stations")

                for marker_id, data in KLANG_BOOM_STATIONS_REFERENCE.items():
                    description = f"{data['zone'].capitalize()} zone - Priority {data['priority']}"

                    if has_position_source:
                        cursor.execute("""
                            INSERT INTO project_markers (
                                marker_id, marker_type, name, description,
                                location_x, location_y, location_z,
                                color, priority, status,
                                installation_date, position_source
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), 'auto')
                        """, (marker_id, 'boom_trap', data['name'], description,
                              data['x'], data['y'], data['z'],
                              '#FF6B35', data['priority'], 'ACTIVE'))
                    else:
                        cursor.execute("""
                            INSERT INTO project_markers (
                                marker_id, marker_type, name, description,
                                location_x, location_y, location_z,
                                color, priority, status,
                                installation_date
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
                        """, (marker_id, 'boom_trap', data['name'], description,
                              data['x'], data['y'], data['z'],
                              '#FF6B35', data['priority'], 'ACTIVE'))
            else:
                # Reset existing - preserve manual edits
                logger.log("Resetting existing boom stations")
                logger.log("Preserving manual edits (position_source='manual')")

                manual_count = 0
                updated_count = 0

                for marker_id, data in KLANG_BOOM_STATIONS_REFERENCE.items():
                    # Check if this boom exists and if it's manually edited
                    if has_position_source:
                        cursor.execute("""
                            SELECT position_source FROM project_markers
                            WHERE marker_type = 'boom_trap' AND marker_id = ?
                        """, (marker_id,))
                        result = cursor.fetchone()

                        if result and result[0] == 'manual':
                            manual_count += 1
                            logger.log(f"  Boom {marker_id}: Preserving manual position")
                            continue  # Skip - preserve manual edit

                    # Update this boom (it's either auto or doesn't exist)
                    description = f"{data['zone'].capitalize()} zone - Priority {data['priority']}"

                    if has_position_source:
                        cursor.execute("""
                            INSERT OR REPLACE INTO project_markers (
                                marker_id, marker_type, name, description,
                                location_x, location_y, location_z,
                                color, priority, status,
                                installation_date, position_source
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), 'auto')
                        """, (marker_id, 'boom_trap', data['name'], description,
                              data['x'], data['y'], data['z'],
                              '#FF6B35', data['priority'], 'ACTIVE'))
                    else:
                        cursor.execute("""
                            INSERT OR REPLACE INTO project_markers (
                                marker_id, marker_type, name, description,
                                location_x, location_y, location_z,
                                color, priority, status,
                                installation_date
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
                        """, (marker_id, 'boom_trap', data['name'], description,
                              data['x'], data['y'], data['z'],
                              '#FF6B35', data['priority'], 'ACTIVE'))
                    updated_count += 1

                if manual_count > 0:
                    logger.log(f"✓ Preserved {manual_count} manual edits")
                logger.log(f"✓ Updated {updated_count} auto-generated positions")

            conn.commit()

            logger.section("VERIFICATION")

            # Verify the reset
            cursor.execute("SELECT COUNT(*) FROM project_markers WHERE marker_type = 'boom_trap';")
            final_count = cursor.fetchone()[0]
            logger.log(f"Boom stations after reset: {final_count}")

            # Check coordinate ranges
            cursor.execute("""
                SELECT MIN(location_x), MAX(location_x),
                       MIN(location_y), MAX(location_y)
                FROM project_markers WHERE marker_type = 'boom_trap';
            """)
            bounds = cursor.fetchone()
            logger.log(f"X range: {bounds[0]:.1f} to {bounds[1]:.1f}")
            logger.log(f"Y range: {bounds[2]:.1f} to {bounds[3]:.1f}")

            # Show sample
            cursor.execute("""
                SELECT marker_id, name, location_x, location_y FROM project_markers
                WHERE marker_type = 'boom_trap'
                ORDER BY marker_id
                LIMIT 5
            """)
            sample = cursor.fetchall()
            logger.log(f"Sample after reset (first 5):")
            for row in sample:
                logger.log(f"  ID {row[0]}: {row[1]} at ({row[2]:.1f}, {row[3]:.1f})")

            conn.close()

            if final_count == len(KLANG_BOOM_STATIONS_REFERENCE):
                if existing_count == 0:
                    logger.log("✓ INITIAL SETUP COMPLETE - 40 BOOM STATIONS CREATED")
                    logger.summary(True, f"SUCCESS - Initial setup: {final_count} boom stations created")
                    self.report({'INFO'}, f"✓ Setup complete: {final_count} boom stations initialized")
                else:
                    logger.log("✓ ALL 40 BOOM STATIONS RESTORED FROM REFERENCE")
                    logger.summary(True, f"SUCCESS - Reset {final_count} boom stations from reference")
                    self.report({'INFO'}, f"✓ Reset complete: {final_count} boom stations restored")
                return {'FINISHED'}
            else:
                logger.log(f"WARNING: Expected {len(KLANG_BOOM_STATIONS_REFERENCE)}, got {final_count}", error=True)
                logger.summary(False, f"PARTIAL - Only {final_count} stations created")
                self.report({'WARNING'}, f"Partial setup: {final_count} of {len(KLANG_BOOM_STATIONS_REFERENCE)}")
                return {'FINISHED'}

        except Exception as e:
            logger.log(f"EXCEPTION: {str(e)}", error=True)
            import traceback
            tb_str = traceback.format_exc()
            logger._write(tb_str)
            print(tb_str)
            logger.summary(False, f"FAILED - {str(e)}")
            self.report({'ERROR'}, f"Reset failed: {str(e)}")
            return {'CANCELLED'}


class BIM_OT_clear_ecosystem_model(Operator):
    """Clear all ecosystem monitoring objects from scene"""
    bl_idname = "bim.clear_ecosystem_model"
    bl_label = "Clear Ecosystem Model"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        logger = RiverEcosystemLogger("CLEAR ECOSYSTEM")

        try:
            initial_objects = len(bpy.data.objects)
            initial_collections = len(bpy.data.collections)
            logger.log(f"Initial objects: {initial_objects}")
            logger.log(f"Initial collections: {initial_collections}")

            logger.section("CLEARING ECOSYSTEM MONITORING OBJECTS")
            logger.log("Preserving IFC elements (river geometry)")

            # Use helper function
            removed_collections, removed_objects = clear_ecosystem_objects()

            final_objects = len(bpy.data.objects)
            final_collections = len(bpy.data.collections)

            logger.log(f"Final objects: {final_objects} (removed {removed_objects})")
            logger.log(f"Final collections: {final_collections} (removed {removed_collections})")

            # Count preserved IFC elements
            ifc_count = 0
            for obj in bpy.data.objects:
                if 'ifc_definition_id' in obj:
                    ifc_count += 1

            logger.log(f"Preserved {ifc_count} IFC elements (including river)")

            if removed_collections > 0:
                logger.summary(True, f"CLEARED - {removed_collections} collections, {removed_objects} objects, preserved {ifc_count} IFC")
                self.report({'INFO'}, f"✓ Cleared {removed_objects} objects, kept {ifc_count} IFC elements")
            else:
                logger.summary(False, "No ecosystem objects found to clear")
                self.report({'INFO'}, "No ecosystem objects to clear")

            return {'FINISHED'}

        except Exception as e:
            logger.log(f"ERROR: {e}", error=True)
            import traceback
            logger._write(traceback.format_exc())
            traceback.print_exc()
            logger.summary(False, f"FAILED - {str(e)}")
            self.report({'ERROR'}, f"Failed to clear: {str(e)}")
            return {'CANCELLED'}


# =============================================================================
# Registration
# =============================================================================

classes = (
    BIM_PT_river_ecosystem,
    BIM_OT_test_river_database,
    BIM_OT_reset_boom_stations,
    BIM_OT_run_klang_realistic_monitor,
    BIM_OT_run_infrastructure_model,
    BIM_OT_run_storm_simulation,
    BIM_OT_run_basic_ecosystem,
    BIM_OT_clear_ecosystem_model,
)

def register():
    for cls in classes:
        if not hasattr(bpy.types, cls.__name__):
            bpy.utils.register_class(cls)
    print("✓ River Ecosystem Model UI registered (Item 11)")

def unregister():
    for cls in reversed(classes):
        if hasattr(bpy.types, cls.__name__):
            bpy.utils.unregister_class(cls)